version: 33
jobs:
- name: Push2Github
  steps:
  - !PushRepository
    name: push2github
    remoteUrl: https://github.com/superwhys/venkit
    passwordSecret: token
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  - !TagCreateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: pullFromGithub
  steps:
  - !PullRepository
    name: pullFromGithub
    remoteUrl: https://github.com/superwhys/venkit
    passwordSecret: token
    refs: refs/heads/* refs/tags/*
    withLfs: false
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !ScheduleTrigger
    cronExpression: 0 */2 * * * ?
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
